"""Add room_id to applications table

Revision ID: 7d961e4b544c
Revises: bbef74930fb6
Create Date: 2024-11-26 01:18:18.467531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d961e4b544c'
down_revision = 'bbef74930fb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('room_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_applications_room_id', 'rooms', ['room_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.drop_constraint('fk_applications_room_id', type_='foreignkey')
        batch_op.drop_column('room_id')

    # ### end Alembic commands ###
